### ISSUE TITLE
v1beta1 is being used as the default alias instead of v1

### ISSUE THREAD

**Issue by busunkim96** [googleapis/python-datacatalog#116]
```py
from google.cloud import datacatalog  # this should be 'datacatalog_v1' but is actually 'datacatalog_v1beta1'
from google.cloud import datacatalog_v1beta1
from google.cloud import datacatalog_v1
```
https://github.com/googleapis/python-datacatalog/blob/master/google/cloud/datacatalog/__init__.py#L18
https://github.com/googleapis/python-datacatalog/blob/4bfa587903105cb3de2272618374df0b04156017/synth.py#L28

The am planning on comparing the protos to determine if there are meaningful differences in the protos. If there are breaking changes, this would need to be done in a new major.

CC @tswast @steffnay

**Comment by meredithslota** [comment]
The public protos were just refreshed in late March 2021 (3/29?) so it's possible that this was a side-effect of that. cl/365620142 is the relevant update, I think.
