### ISSUE TITLE
Issue when listing tags in different projects

### ISSUE THREAD

**Issue by andre-sasaki** [googleapis/python-datacatalog#14]
Giving the following scenario, when I try to list tags for the described entry, I don't have the 2 expected results, instead, the function only returns the tag on the Tag Template B.
**Tag Template A**
```
{
	"Project-ID": "project_a",
	"Location": "us-central1",
	"Template-ID": "template_a",
	"FIELDS": ["TAG_A"]
}

```
**Tag Template B**
```
{
	"Project-ID": "project_b",
	"Location": "us-central1",
	"Template-ID": "template_b",
	"FIELDS": ["TAG_B"]
}
```

**Entry**
```
{
	"Type":	"TABLE",
	"System":	"BIGQUERY",
	"Table-Type":	"BIGQUERY_TABLE",
	"Project-ID":	"project_b",
	"Location":	"eu",
	"TAGS":
			{
				"Column":[
							{
								"ID": "column_a",
								"TAG" "TAG_A"
							},
							{
								"ID": "column_b",
								"TAG" "TAG_B"
							}
						]
			}
}
```

**Python mocked code**
```
client = datacatalog.DataCatalogClient()
list_tags = list(client.list_tags(entry_path))
```
**Python Result**
```
[
	{'name': 'projects/project_b/locations/eu/entryGroups/@bigquery/entries/entry_id/tags/tag_id',
	 'template': 'projects/project_b/locations/us-central1/tagTemplates/template_b', 
	 'fields': {
	 		'template_b': 
	 			{
	 				'displayName': 'TAG_B'
	 			}
	 		 }, 
	 'column': 'column_b', 
	 'templateDisplayName': 'template_b'
	 }
 ]
```

**REST API Result**
projects.locations.entryGroups.entries.tags.list
```
 [
	{'name': 'projects/project_b/locations/eu/entryGroups/@bigquery/entries/entry_id/tags/tag_id',
	 'template': 'projects/project_b/locations/us-central1/tagTemplates/template_b', 
	 'fields': {
	 		'template_b': 
	 			{
	 				'displayName': 'TAG_B'
	 			}
	 		 }, 
	 'column': 'column_b', 
	 'templateDisplayName': 'template_b'
	 },
	{'name': 'projects/project_b/locations/eu/entryGroups/@bigquery/entries/entry_id/tags/tag_id',
	 'template': 'projects/project_a/locations/us-central1/tagTemplates/template_a', 
	 'fields': {
	 		'template_a': 
	 			{
	 				'displayName': 'TAG_A'
	 			}
	 		 }, 
	 'column': 'column_a', 
	 'templateDisplayName': 'template_a'
	 }
 ]

```
#### Environment details

  - OS type and version:
  - Python version: `python --version`
  - pip version: `pip --version`
  - `google-cloud-datacatalog` version: `pip show google-cloud-datacatalog`

#### Steps to reproduce

  1. ?
  2. ?

#### Code example

```python
# example
```

#### Stack trace
```
# example
```

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by maroshmka** [comment]
I was testing some search features using this client in our app. I couldn't figured out why it doesn't work, but I created the tags manually in UI under different project (I haven't noticed Im switched there).

This leads me to question, how should this work? If the tag template is created in project A, should service account with permissions to project B see tags created with template from project A? I don't really know the answer and I don't see any security issue this may lead to right now. Just wanted to raise this question here :)
