### ISSUE TITLE
Update samples to V1 version

### ISSUE THREAD

**Issue by mesmacosta** [googleapis/python-datacatalog#21]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

 **Is your feature request related to a problem? Please describe.**
With release of V1 library, we must update the samples to instruct users to use the supported version. Right now samples are using the v1beta1 version, which might lead users to use the beta version.

 **A clear and concise description of what you want to happen. **
Update samples to V1 version.
 **Additional context**
N/A

**Comment by meredithslota** [comment]
Closing in favor of #78.
