### ISSUE TITLE
AttributeError: module 'google.cloud.datacatalog_v1' has no attribute 'GetIamPolicyRequest'

### ISSUE THREAD

**Issue by guillermo-uala** [googleapis/python-datacatalog#336]
As doc says https://googleapis.dev/python/datacatalog/latest/datacatalog_v1/policy_tag_manager.html

```
from google.cloud import datacatalog_v1

# Create a client
client = datacatalog_v1.PolicyTagManagerClient()

# Initialize request argument(s)
request = datacatalog_v1.GetIamPolicyRequest(
    resource="resource_value",
    )
```
Throw this error:

`AttributeError: module 'google.cloud.datacatalog_v1' has no attribute 'GetIamPolicyRequest'`

Im on python 3.7 and google-cloud-datacatalog==3.7.1

**Comment by meredithslota** [comment]
@parthea This might be an issue with the library and might be an issue with the sample — can you help me route it appropriately?

**Comment by parthea** [comment]
There is an open bug with the sample code generator (snippetgen): https://github.com/googleapis/gapic-generator-python/issues/1263

**Comment by meredithslota** [comment]
Looks like the linked bug is resolved — do you know when changes will roll out? 

@guillermo-uala — a comment in that bug report suggests a better path, hope this helps in the meantime: https://github.com/googleapis/gapic-generator-python/issues/1263#issuecomment-1093486715

**Comment by dandhlee** [comment]
Seems like the [doc](https://googleapis.dev/python/datacatalog/latest/datacatalog_v1/policy_tag_manager.html#google.cloud.datacatalog_v1.services.policy_tag_manager.PolicyTagManagerAsyncClient.create_policy_tag) was updated before the snippet changes were rolled out, but the other updates have already been merged in https://github.com/googleapis/python-datacatalog/pull/343/files.
