### ISSUE TITLE
There is no sample code for PolicyTagManagerClient.create_taxonomy

### ISSUE THREAD

**Issue by ricardolsmendes** [googleapis/python-datacatalog#36]
[PolicyTagManagerClient class was added to this library in version 0.5.0](https://googleapis.dev/python/datacatalog/latest/changelog.html#id6), but there is no sample code demonstrating how it works yet.

**Comment by meredithslota** [comment]
Made obsolete by https://github.com/googleapis/nodejs-datacatalog/pull/288 - closing.
