### ISSUE TITLE
ModifyEntryOverviewRequest not available

### ISSUE THREAD

**Issue by mircozamprogno** [googleapis/python-datacatalog#431]
Hi, 

regardless what documented, I am not able to modify an entry overview, based on the code it should be available.
Just testing [this article](https://cloud.google.com/python/docs/reference/datacatalog/latest/google.cloud.datacatalog_v1.services.data_catalog.DataCatalogClient#google_cloud_datacatalog_v1_services_data_catalog_DataCatalogClient_modify_entry_overview) it should work but this is the message I have.

<img width="846" alt="Screen Shot 2022-09-15 at 13 11 01" src="https://user-images.githubusercontent.com/33618954/190393512-1c2dc9e9-7d8f-4405-af2f-38d5287b5078.png">

let me know

thanks

**Comment by parthea** [comment]
After discussion offline we were able to determine that the name should the full resource name to the entry in the format `projects/{project}/locations/{location}/entryGroups/{entrygroup}/entries/{entries}`

Sample code:

```
from google.cloud.datacatalog_v1 import ModifyEntryOverviewRequest
from google.cloud.datacatalog_v1 import EntryOverview
from google.cloud import  datacatalog_v1

datacatalog = datacatalog_v1.DataCatalogClient()

request = ModifyEntryOverviewRequest(name=""<full resource name to the entry>", entry_overview=EntryOverview(overview="this is an overview"))
datacatalog.modify_entry_overview(request=request)
```

**Comment by parthea** [comment]
I'm going to close this issue as resolved. We already have a project in progress to improve the autogenerated snippets.
