### ISSUE TITLE
Docs have "latest" as v1.0.0 but v2.0.0 was released 8/24

### ISSUE THREAD

**Issue by meredithslota** [googleapis/python-datacatalog#67]
Was checking to see if https://github.com/googleapis/python-datacatalog/issues/4 was resolved and noticed that the docs don't seem to have captured the latest release. 

Latest release was v2.0.0 on 8/24: https://github.com/googleapis/python-datacatalog/releases/tag/v2.0.0  and on PyPi https://pypi.org/project/google-cloud-datacatalog/2.0.0/

https://googleapis.dev/python/datacatalog/latest/index.html has v1.0.0 in the drop-down menu as "latest" and doesn't seem to have the v2.0.0 listed at all, and is still exhibiting the menu nav issues described here: https://github.com/googleapis/python-bigquery-storage/issues/18 which was theoretically fixed here: https://github.com/googleapis/gapic-generator-python/issues/430 but possibly requires some changes to be seen.

**Comment by busunkim96** [comment]
This is now resolved.
