### ISSUE TITLE
location_path helper method removed in v2.0.0 is not mentioned in the Migration Guide

### ISSUE THREAD

**Issue by ricardolsmendes** [googleapis/python-datacatalog#68]
The `location_path` helper method is not available in DataCatalogClient v2.0.0, although the [2.0.0 Migration Guide](https://github.com/googleapis/python-datacatalog/blob/master/UPGRADING.md#project-path-helper-methods) does not mention it. Is this the intended behavior starting from 2.0.0? If so, should I submit a PR to update the migration guide?

Thanks,

**Comment by busunkim96** [comment]
@ricardolsmendes Yes, it looks like we missed adding this to the migration guide. A PR would be very much appreciated. :)

**Comment by ricardolsmendes** [comment]
Thanks, @busunkim96! I'm going to submit a PR asap.

**Comment by ricardolsmendes** [comment]
Hi @busunkim96,
I've just submitted https://github.com/googleapis/python-datacatalog/pull/70. Please let me know your thoughts!

**Comment by ricardolsmendes** [comment]
Closing this issue because updating the upgrade guide to be from 1.0 to 3.0 is under discussion on #76...
