### ISSUE TITLE
Duplicate code in synth.py

### ISSUE THREAD

**Issue by tswast** [googleapis/python-datacatalog#94]
Samples templates are defined twice. Only once is needed (I assume).

https://github.com/googleapis/python-datacatalog/blob/fda528a1da2ec1dbf6b3ad33eb2d33780a77f3d9/synth.py#L70

https://github.com/googleapis/python-datacatalog/blob/fda528a1da2ec1dbf6b3ad33eb2d33780a77f3d9/synth.py#L80

**Comment by meredithslota** [comment]
Looks like this got added here: https://github.com/googleapis/python-datacatalog/pull/54/files#diff-296a39f9422dac004121c56b959022e9ad234263312c6433f8c58e2e6cd0b61e during migration to microgenerator. Seems safe to remove.
